apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.postgresqlHost | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.postgresqlPort | quote }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Values.postgresql.postgresqlHost .Values.postgresql.postgresqlPort .Values.postgresql.postgresqlDatabase  | quote }}
        image: postgres:latest
        # NOTICE: you can use https://bcrypt-generator.com/ to generate hashes for the users below:
        # - rounds must be 7
        # - input string is like Pa55-gateway
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              --- gateway
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$fUr48EgHmwk/RVJGrVaE2O8fdg8Oj0UZM/8XGDEsYc0ZsQN3nyh8m',
                                  'gateway@khopp.online',
                                  'gateway',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
              	RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
              )
              	INSERT INTO public.user_role(user_id, role_name)
              	SELECT id, role_name FROM inserted_id
              	JOIN roles on 1=1;

              --- sessions
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$P.aXRf04s7x7vl98JQLZ.OO7BRUeAz9GiERfThUK6ufCnZ7gqtLeO',
                                  'sessions@khopp.online',
                                  'sessions',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
              	RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
              )
              	INSERT INTO public.user_role(user_id, role_name)
              	SELECT id, role_name FROM inserted_id
              	JOIN roles on 1=1;

              --- users
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$ujwNRDXSoGL3QXFHV0cgi.i1RO2BagpUATR2Tn/qDJtpZ6Jmi0kva',
                                  'users@khopp.online',
                                  'users',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
              	RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
              )
              	INSERT INTO public.user_role(user_id, role_name)
              	SELECT id, role_name FROM inserted_id
              	JOIN roles on 1=1;

              --- userpurger
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$E3BOV3Rd6Vn.5Tz/AlTQlOzDRqiipvHBHNCgMDAKIz4DvYvklescy',
                                  'userpurger@khopp.online',
                                  'userpurger',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
                RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
              )
                INSERT INTO public.user_role(user_id, role_name)
                SELECT id, role_name FROM inserted_id
                JOIN roles on 1=1;

              --- poi
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$QLVedwhPtBLZNzXuRxlju.B7DhlWjuEGf2ZHB4qj1YPS9szcIDOPC',
                                  'poi@khopp.online',
                                  'poi',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
              	RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
                 UNION SELECT 'POI'
              )
              	INSERT INTO public.user_role(user_id, role_name)
              	SELECT id, role_name FROM inserted_id
              	JOIN roles on 1=1;

              --- routes
              WITH inserted_id(id) as (
                 INSERT INTO public.users(
                              password,
                              email,
                              login,
                              closing_date,
                              activated_at,
                              expired_at,
                              created_at,
                              updated_at,
                              state,
                              email_status)
                              VALUES
                              (
                                  '$2a$07$iaurxBMwlBt5xKp0c7htg.lsOVjmVY8xk194HdH5fAEym0Tn8D3dS',
                                  'routes@khopp.online',
                                  'routes',
                                  '2070-02-11',
                                  NOW(),
                                  '2070-02-11',
                                  NOW(),
                                  NOW(),
                                  'CONFIRMED',
                                  'VERIFIED'
                              )
              	RETURNING id
              ),
              roles(role_name) as (
                 SELECT 'SERVICE'
                 UNION SELECT 'POI_READER'
              )
              	INSERT INTO public.user_role(user_id, role_name)
              	SELECT id, role_name FROM inserted_id
              	JOIN roles on 1=1;
            EOF

  backoffLimit: 0
