---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Chart.Name }}
  labels:
    app: redis-{{ .Chart.Name }}
spec:
  type: NodePort
  ports:
   - port: 6379
  selector:
    app: redis-{{ .Chart.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-{{ .Chart.Name }}
spec:
  serviceName: "redis-{{ .Chart.Name }}"
  replicas: 1
  selector:
    matchLabels:
      app: redis-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: redis-{{ .Chart.Name }}
    spec:
      containers:
      - name: redis
        image: redis:5.0.6
        command:
          - redis-server
          - --requirepass
          - redis-db-password
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data    
      #volumes:
        #- name: data
          #emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          