apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    app-type: spring-boot
    management.port: http
    management.address: "{{ .Chart.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}