---
apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ .Chart.Name }}
  labels:
    app: postgres-{{ .Chart.Name }}
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres-{{ .Chart.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-{{ .Chart.Name }}
spec:
  serviceName: "postgres-{{ .Chart.Name }}"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Chart.Name }}
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgredb
        env:
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.postgresqlUsername | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: standard
      resources:
        requests:
          storage: 1Gi
