{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ tpl .Values.ingress.host . | quote }}
    http:
      paths:
        - path: /(.*)
          backend:
            serviceName: {{ .Chart.Name }}
            servicePort: http
{{- end }}