replicaCount: 1

image:
  repository: khopp.online/online.khopp.users
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}  

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 6565
    protocol: TCP
  - name: http-jmx
    containerPort: 9010
    protocol: TCP

resources:
  limits:
    memory: 1024M
    cpu: 1
  requests:
    memory: 400M
    cpu: 0.1

#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  postgresqlHost: "postgres-users"
  postgresqlPort: "5432"
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: users 

livenessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

healthCheck:
  port: http
  path: /management/info

spring:
  profile: default