---
apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ .Chart.Name }}
  labels:
    app: postgres-{{ .Chart.Name }}
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres-{{ .Chart.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-{{ .Chart.Name }}
spec:
  serviceName: "postgres-{{ .Chart.Name }}"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Chart.Name }}
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgredb
        env:
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.postgresqlUsername | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
#      volumes:
#        - name: postgredb-persistent-storage
#          persistentVolumeClaim:
#            claimName: postgres-pvc
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: localstorage
      resources:
        requests:
          storage: 1Gi
#
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: localstorage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: Immediate
#reclaimPolicy: Delete
#allowVolumeExpansion: True
#
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: postgres
#  labels:
#    type: local
#spec:
#  storageClassName: localstorage
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/postgres"